name: "Scrape DRG Data"

on:
  schedule: 
    - cron: '0 11 * * 4'  # every Thursday at 11AM UTC

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check python version
        run: python3 --version

      - name: Install python dependencies
        run: python3 -m pip install requests

      - name: Run scraper
        run: python3 ./scraper.py

      - name: Commit data
        run: |
          git config user.email woesbot@users.noreply.github.com
          git config user.name woesbot
          git add -A
          git commit -m "Automated retrieval ($(date --iso-8601=seconds))"
          git push
